### ISSUE TITLE
Add cache filter to dashboard

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#25]
Add a cache filter option on the dashboard in the top right.

![image](https://user-images.githubusercontent.com/67169954/95921598-cbb2fa00-0d6e-11eb-89b5-6733bc0c5375.png)

**Comment by epratt5** [comment]
It's currently sorted by Type of Cache. Is that what you want? Or a different field?

**Comment by kkay82** [comment]
I guess I was thinking along the lines of how you have the selector to show all shelters, just closed ones, just open ones, or spontaneous if one exists. I was thinking there would just be one more that said caches. 

Now that I think of it, caches aren't open or closed, so maybe they should always show on the dashboard.

**Comment by epratt5** [comment]
Either way is easy to do. Just let me know what you think after you play around with it. :)

**Comment by kkay82** [comment]
I like the button you put there. Can we make the filters for caches the three options we have under type of cache?

- Loose Supplies

- Trailer (driveable)

- Trailer (towable)

**Comment by epratt5** [comment]
I made the filter look like the Status filter, using buttons instead of a dropdown. The buttons for each option only shows if there is an item with that information completed. They will all have the same icon because the layer is symbolized by location only. If you want them symbolized by Type of Cache, I can look into that, but it will have to be a different icon that is possibly created by us.

**Comment by kkay82** [comment]
This is amazing, nice work. Same icon is just fine, closing this one.
